# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.13.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - run: mkdir -p /tmp/artifacts
      - run:
          name: Build and push docker image
          command: |
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -t resultadosdigitais/bigtable-autoscaler-operator:$SHORT_GIT_HASH .
            docker push resultadosdigitais/bigtable-autoscaler-operator:$SHORT_GIT_HASH
            docker inspect --format='{{index .RepoDigests 0}}' resultadosdigitais/bigtable-autoscaler-operator:$SHORT_GIT_HASH > /tmp/artifacts/bigtable-autoscaler-operator-docker-image-digest.txt
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker tag resultadosdigitais/bigtable-autoscaler-operator:$SHORT_GIT_HASH resultadosdigitais/bigtable-autoscaler-operator:stable
              docker push resultadosdigitais/bigtable-autoscaler-operator:stable
            fi
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts

  release:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      - run: mkdir -p /tmp/artifacts
      - run:
          name: Releases a new version
          command: |
            echo "OLÁ"
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts

workflows:
  test-and-build:
    jobs:
      - test
      - build:
          context:
            - dockerhub-credentials
  release:
    jobs:
      - release:
          context:
            - dockerhub-credentials
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]+\.?)+$/
