# permissions for end users to view bigtableautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bigtableautoscaler-viewer-role
rules:
- apiGroups:
  - bigtable.bigtable-autoscaler.com
  resources:
  - bigtableautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bigtable.bigtable-autoscaler.com
  resources:
  - bigtableautoscalers/status
  verbs:
  - get
