---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bigtable-autoscaler-system
  name: bigtable-autoscaler-service-account-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: bigtable-autoscaler-system
  name: bigtable-autoscaler-service-account-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bigtable-autoscaler-service-account-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: bigtable-autoscaler-system
