// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GoogleCloudClient is an autogenerated mock type for the GoogleCloudClient type
type GoogleCloudClient struct {
	mock.Mock
}

// GetCurrentCPULoad provides a mock function with given fields:
func (_m *GoogleCloudClient) GetCurrentCPULoad() (int32, error) {
	ret := _m.Called()

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrentNodeCount provides a mock function with given fields: clusterID
func (_m *GoogleCloudClient) GetCurrentNodeCount(clusterID string) (int32, error) {
	ret := _m.Called(clusterID)

	var r0 int32
	if rf, ok := ret.Get(0).(func(string) int32); ok {
		r0 = rf(clusterID)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
