// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "bigtable-autoscaler.com/m/v2/pkg/interfaces"
	mock "github.com/stretchr/testify/mock"

	monitoring "google.golang.org/genproto/googleapis/monitoring/v3"
)

// MetricClientWrapper is an autogenerated mock type for the MetricClientWrapper type
type MetricClientWrapper struct {
	mock.Mock
}

// ListTimeSeries provides a mock function with given fields: ctx, req
func (_m *MetricClientWrapper) ListTimeSeries(ctx context.Context, req *monitoring.ListTimeSeriesRequest) interfaces.TimeSeriesIteratorWrapper {
	ret := _m.Called(ctx, req)

	var r0 interfaces.TimeSeriesIteratorWrapper
	if rf, ok := ret.Get(0).(func(context.Context, *monitoring.ListTimeSeriesRequest) interfaces.TimeSeriesIteratorWrapper); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.TimeSeriesIteratorWrapper)
		}
	}

	return r0
}
