// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	monitoring "google.golang.org/genproto/googleapis/monitoring/v3"
)

// MetricClientWrapper is an autogenerated mock type for the MetricClientWrapper type
type MetricClientWrapper struct {
	mock.Mock
}

// NextMetric provides a mock function with given fields: ctx, req
func (_m *MetricClientWrapper) NextMetric(ctx context.Context, req *monitoring.ListTimeSeriesRequest) (int32, error) {
	ret := _m.Called(ctx, req)

	var r0 int32
	if rf, ok := ret.Get(0).(func(context.Context, *monitoring.ListTimeSeriesRequest) int32); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *monitoring.ListTimeSeriesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
