// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	apiv3 "cloud.google.com/go/monitoring/apiv3"

	gax "github.com/googleapis/gax-go/v2"

	mock "github.com/stretchr/testify/mock"

	monitoring "google.golang.org/genproto/googleapis/monitoring/v3"
)

// MonitoringMetricClient is an autogenerated mock type for the MonitoringMetricClient type
type MonitoringMetricClient struct {
	mock.Mock
}

// ListTimeSeries provides a mock function with given fields: ctx, req, opts
func (_m *MonitoringMetricClient) ListTimeSeries(ctx context.Context, req *monitoring.ListTimeSeriesRequest, opts ...gax.CallOption) *apiv3.TimeSeriesIterator {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *apiv3.TimeSeriesIterator
	if rf, ok := ret.Get(0).(func(context.Context, *monitoring.ListTimeSeriesRequest, ...gax.CallOption) *apiv3.TimeSeriesIterator); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv3.TimeSeriesIterator)
		}
	}

	return r0
}
