// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TimeSeriesIteratorWrapper is an autogenerated mock type for the TimeSeriesIteratorWrapper type
type TimeSeriesIteratorWrapper struct {
	mock.Mock
}

// Points provides a mock function with given fields:
func (_m *TimeSeriesIteratorWrapper) Points() ([]int32, error) {
	ret := _m.Called()

	var r0 []int32
	if rf, ok := ret.Get(0).(func() []int32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int32)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
