apiVersion: bigtable.bigtable-autoscaler.com/v1
kind: BigtableAutoscaler
metadata:
  name: bigtableautoscaler-sample
spec:
  bigtableClusterRef:
    projectId: cdp-development
    instanceId: clustering-engine
    clusterId: clustering-engine-c1
  serviceAccountSecretRef:
    namespace: default
    name: staging-service-account
    key: service-account
  minNodes: 1
  maxNodes: 2
  targetCPUUtilization: 50
